Vizzuality/playbook

- _config.yml
> Hide download buttons

- README.md
As discussed in the decisions team, it would be useful to have some rules of thumb to help people create new guidelines and make sure we are all consistent.
This is work in progress, active participation is encouraged
Proposed text:
A guideline is a written statement that helps make autonomous decisions.
All guidelines are stored in this repository. You can find them either by using keyword search or navigating the categories.
You need to follow the **advice process** to arrive at a decision. Anyone in the advice process can initiate a consent process to create a guideline based on the advice.
Sometimes you may discover that an existing guideline does not cover your specific case, is out of sync with current best practice or contradicts other guidelines. In such case you don't have to …
> Guidelines for Guideline creation/approval

- README.md
It has been pointed out that before starting a pull request you need to make changes on a branch, which was not well described. This PR adds the following instructions:
Since we're using GitHub as a guideline repository, the natural way of suggesting changes is via the mechanism of [Pull Requests](https://help.github.com/articles/using-pull-requests)
The starting point is to have your content saved in a branch of the repository (please do not commit directly into master, unless maybe you see a typo). There are a few ways technically to do that, broadly speaking:
- you can clone the repo to your machine, create a branch, make changes and push like you'd do with code
- you can use GitHub's interface
When using the GitHub interface, first create a new branch by using the "Branch" dropdown, …
> More details on starting pull requests

- feedback-loops/Ongoing Feedback/giving_feedback.md
- feedback-loops/Ongoing Feedback/receiving_feedback.md
- feedback-loops/roadmap.md
- Separate Giving/Receiving Feedback overviews
- Flesh out when to give feedback section
- Add automated testing to roadmap
- Update roadmap
***
- Build concrete guidline doc
- Outline general rules for framing the system (frequency, who-who, how, central axioms)
- General framework for different interactions
- Champions/Ambassadors
- Scaffold behaviour (Phase 2)
***
Things that need to be discussed moving forwards. See the [open-questions document](https://docs.google.com/document/d/1eGlzH5fOxIchVyLRipWBrNBIgdQ18-BHVmVD-PnEmoI/edit#heading=h.aqcfnjgggoxb) to keep up-to-date.
Areas/Contexts that have not been addressed:
1. Replacing/Augmenting Performance Reviews
At this stage have addressed formative (ongoing) feedback, but we are lacking a solution to summative (end of line) feedback, …
> Implement Jamie's suggestions

- conflict-resolution/index.md
- projects/external-comms/index.md
In this guideline we want to outline some guidance to help you prevent conflict in the first place, then some steps you can take when you have a conflict you want to resolve.
_If you have a conflict you should resolve it. If you detect a conflict you must help the people involved. The responsibility for resolving our conflicts as a company, is shared._
1. We use the Nonviolent Communication (NVC) process. This means being open to talk about times when our strategies violate or don't fulfill our colleague's needs. This means focussing on needs and objective things, not opinons. 
2. We don’t blame problems on others. If something doesn't go as we planned, it's a chance to learn and improve 
3. We take ownership for our thoughts, beliefs, words, and actions  
4. We don’t spread rumors
5. We …
> Guidelines for conflict resolution

- information-flow/documents.md
- information-flow/index.md
- information-flow/status-updates/thursday-2-august-2018.md
In the last few days, we have been collecting the feedback from vizzcamp and we now have a plan of going forward.
Our conclusion collecting the feedback.
Our concepts
- transparency
- reliability
- accessibility
- productivity
have overall been validated, but we have been too abstract. We focused on too many topics and looking at other groups at vizzcamps we saw that they were focusing on a handful of concrete topics and giving concrete solutions for those.
Focusing on solving the most important issues: **mainly project communications** (we’ll touch upon other things as well)
Let’s not reinvent the wheel! **Doing an archeology of existing guidelines to see what has been documented previously in vizzuality**
what we have found is that there are plenty and plenty of guidelines already …
> information flow, actions after vizzcamp

- decision-making/index.md
This is the final document with 3 sections omitted - I thought they don't fit in here, but let me know if you think they should be in here:
- "Current situation" - it's hard to see the connection with that part and the rest of the document, because the problems identified there seem broader than just decision making
- evaluation of Github & Loomio - I have a feeling this requires separate attention
- roadmap - already out of date, so probably needs a re-think and perhaps coordination with other systems
-----------------------
This is a proposal for a decision making system at Vizzuality. The goal of the proposed changes is to empower individuals to make decisions, because we trust people will make the best decisions.
We arrived at it by reviewing our current decision making processes and …
> Decision making proposal

- purpose/index.md
In this Pull Request I'm adding our vision and strategic priorities. I am going to ask the company to provide any blocking comments on the visions by the end of Tuesday (3 working days), before releasing the strategic priorities for discussion. 
#**Purpose.** 
> **Vizzuality's purpose is to reach a fair and sustainable planet by creating tools that radically empower people to make positive changes now.**
This vision was accepted by consent in a whole-company workshop in May 2018. 
Vision statements are meant to be a more practical and measurable expression of the Purpose. Within five years, what would we like to achieve? It is intended that these statements help everyone at the company understand what we are aiming for, and also to help them make decisions about where to focus their …
> Vision and strategy Proposal

- resource-allocation/benefits.md
This PR includes the list of the current benefits with the general and the specific ones by the different offices.
> Include current benefits

- purpose/index.md
In this PR we’re asking for your comments about the 2 Strategic Priorities for the rest of 2018 and the 7 priority activities to achieve them. 
We have two main priorities for the next six months.
1. Increase the urgency of our work and complete projects more quickly.
Under this priority we will undertake five main activities:
* The 6 systems we’re creating are built around increasing speed and quality and are consentmentized and operational by the end of 2018.
* Build an organistional structure that empowers individual ownership of our work, rewarding positive behaviour and a drive towards our results.
* Build a strategy for better communication during meetings (including good practices and equipment).
* Hire staff with different skills/ backgrounds who can create new tools, data, …
> Strategic Priorities for rest of 2018

- projects/design-sprint-guidelines/concept.md
- projects/design-sprint-guidelines/content.md
- projects/design-sprint-guidelines/description.md
- projects/design-sprint-guidelines/headline-persona-review.md
- projects/design-sprint-guidelines/ice-breakers.md
- projects/design-sprint-guidelines/index.md
- projects/design-sprint-guidelines/introductions.md
- projects/design-sprint-guidelines/journeys.md
- projects/design-sprint-guidelines/landscape.md
- projects/design-sprint-guidelines/learned.md
- projects/design-sprint-guidelines/network-map.md
- projects/design-sprint-guidelines/personas.md
- projects/design-sprint-guidelines/preparing-a-sprint.md
- projects/design-sprint-guidelines/problems.md
- projects/design-sprint-guidelines/sketching.md
- projects/design-sprint-guidelines/use-cases.md
- projects/design-sprint-guidelines/wntbt.md
- projects/design-sprint-guidelines/yesand.md
- projects/index.md
Turns out I’m not very good at markdown and I made some mistakes, but I couldn’t catch them till I merged to master and saw them on the site
itself. This PR should fix that so you can actually see/ click between
the guidelines.
> some more styling for design sprint guidelines

- guidelines/hiring.md
As per the outdated PR (https://github.com/Vizzuality/playbook/pull/39):
> I updated the guidelines to match with what we've been doing so far, and what we said we'd do in the hiring retrospective.
> Hiring guidelines revamp (rebased with updated master)

- guidelines/index.md
This updates the index.md page of the operational guidelines for the benefit of those using the main front-end of the playbook.
> Update index of operational guidelines

- projects/retrospective/index.md
This PR is aimed to review the Retrospective process based on our latest experience
-We've removed the use of post-its
-We have added valuable observations that can improve the conversation and the result
-We've added an important chapter about what to do after the Retrospective with all the information. 
-There is an important point still in process and that is the "Long term". Ideas welcome.
> retrospective process revisited and post-retrospcetive actions added

- guidelines/security.md
Since this is pretty minor, I'd say merge in a week (28/03/2019) unless someone is against it
> Document 2FA is now required on github accounts

- purpose/index.md
Updates Vizz's purpose to 2020 version as per webpage.
> update purpose description

- purpose/index.md
Reverts Vizzuality/playbook#60
> Revert "update purpose description"

- guidelines/salary-review-2021.md
The proposal has passed following a group decision making by consent, with no objections.
> Added guideline about salary review conversations 2021

- guidelines/index.md
- guidelines/slack-guidelines.md
```
This PR adds slack-guidelines.md which contains Information on how to use Slack (linked to the Slack documentation), some recommendations and usage guidelines to: (1) help on transparency, organisation of information, (2) reduce noise and lack of focus, which lead to more efficiency and better well being
Anyone can review this PR.
As per our Playbook, one of our default group decision making tools is “Consent” and we will be using this tool on this occasion. “Consent” ensures that no one “strongly opposes” (objects) a course of action, while allowing progress to move forward. 
When reading the proposal please reflect on the following:
Do you have any reason(s) why adopting this proposal would cause harm or move us backwards as a team?
Is this good enough for now, safe enough to try? …
```
> Added Slack Guidelines

- projects/index.md
Adding an index to the porject Life Cycle Page.
> Project lifecycle index

- index.md
- projects/index.md
Changing the name of the Bullet point _Project Development_ to **Project Life Cycle** and taking away one sentence to ask BD to add a part (it was a note).
> Project lifecycle corrections ahc

- README.md
Updated readme file with information on using Blogin. [Proposal accepted ](https://vizzuality.blogin.co/posts/proposal-to-update-the-readme-file-of-our-playbook-134264)
> Update/readme file to include information on proposal via Blogin
